In [69]:
import numpy as np

In [70]:
d=[[[1,2],[3,5]],[[6,4],[3,2]]]
arr=np.array(d)

In [71]:
arr

array([[[1, 2],
        [3, 5]],

       [[6, 4],
        [3, 2]]])

In [72]:
arr.shape

(2, 2, 2)

In [73]:
len(arr)

2

In [74]:
 arr.size

8

In [75]:
arr.dtype


dtype('int32')

In [76]:
np.info(arr)

class:  ndarray
shape:  (2, 2, 2)
strides:  (16, 8, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x17eed2274b0
byteorder:  little
byteswap:  False
type: int32


In [77]:
arr=np.zeros((10,11))

In [78]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
a=np.array(d)

In [80]:
a=np.random.randint(123,size=(4,3))

In [81]:
a

array([[ 72,  86,  21],
       [  9,  69,  51],
       [ 65,  43,   5],
       [ 75, 109,  34]])

In [82]:
arr=np.arange(5,15,2)

In [83]:
arr

array([ 5,  7,  9, 11, 13])

In [84]:
a=np.random.randint(low=4,high=10,size=(4,4))
b=np.random.randint(low=4,high=10,size=(4,4))

In [85]:
a

array([[9, 9, 8, 6],
       [8, 5, 9, 6],
       [4, 7, 6, 9],
       [9, 6, 7, 7]])

In [86]:
b

array([[4, 4, 9, 8],
       [8, 7, 7, 6],
       [4, 6, 6, 8],
       [6, 5, 4, 6]])

In [87]:
a.dot(b)

array([[176, 177, 216, 226],
       [144, 151, 185, 202],
       [150, 146, 157, 176],
       [154, 155, 193, 206]])

In [88]:
a*b

array([[36, 36, 72, 48],
       [64, 35, 63, 36],
       [16, 42, 36, 72],
       [54, 30, 28, 42]])

In [89]:
np.power(a,2)

array([[81, 81, 64, 36],
       [64, 25, 81, 36],
       [16, 49, 36, 81],
       [81, 36, 49, 49]], dtype=int32)

In [90]:
a==b

array([[False, False, False, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False, False, False, False]])

In [91]:
a>b

array([[ True,  True, False, False],
       [False, False,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True,  True]])

In [92]:
np.array_equal(a,b)

False

In [93]:
a.max()

9

In [94]:
a


array([[9, 9, 8, 6],
       [8, 5, 9, 6],
       [4, 7, 6, 9],
       [9, 6, 7, 7]])

In [95]:
a.min()

4

In [96]:
a.mean(axis=1)

array([8.  , 7.  , 6.5 , 7.25])

In [97]:
d=np.transpose(a)

In [98]:
d

array([[9, 8, 4, 9],
       [9, 5, 7, 6],
       [8, 9, 6, 7],
       [6, 6, 9, 7]])

In [99]:
c=np.arange(0,10,2)

In [100]:
c

array([0, 2, 4, 6, 8])

In [101]:
z=np.append(c,12)

In [102]:
z

array([ 0,  2,  4,  6,  8, 12])

In [103]:
z=np.insert(c,3,100)

In [104]:
z

array([  0,   2,   4, 100,   6,   8])

In [105]:
np.delete(c,2,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
s=np.split(d,2,axis=1)

In [106]:
s

[array([[9, 7],
        [9, 8],
        [9, 4],
        [6, 6]]),
 array([[5, 5],
        [7, 6],
        [9, 9],
        [8, 4]])]

In [107]:
f=s[0]

In [108]:
f

array([[9, 7],
       [9, 8],
       [9, 4],
       [6, 6]])

In [109]:
h=s[1]

In [110]:
h

array([[5, 5],
       [7, 6],
       [9, 9],
       [8, 4]])

In [111]:
f+h

array([[14, 12],
       [16, 14],
       [18, 13],
       [14, 10]])

In [112]:
import pandas as pd


In [65]:
d=[23,34,56]
i=['a','b','c']

In [66]:
pd.Series(data=d,index=i)

a    23
b    34
c    56
dtype: int64

In [67]:
df=pd.DataFrame(d,i)

In [50]:
df

0
a  23
b  34
c  56