In [1]:
import numpy as np

In [2]:
a=np.array([1,2])
s=0
for i in range(len(a)):
    s=s+a[i]
print(s)

3


In [3]:
x=np.array([[1,2],[4,5]])
y=np.array([[7,8],[10,11
                  ]])

In [4]:
x

array([[1, 2],
       [4, 5]])

In [5]:
y

array([[ 7,  8],
       [10, 11]])

In [6]:
np.concatenate((x,y))

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [7]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  7,  8],
       [ 4,  5, 10, 11]])

In [8]:
np.stack((x,y))

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [9]:
np.dstack((x,y))

array([[[ 1,  7],
        [ 2,  8]],

       [[ 4, 10],
        [ 5, 11]]])

In [10]:
x

array([[1, 2],
       [4, 5]])

In [11]:
a=[]
for i in range(len(x)):
    for j in range(len(x[i])):
      
        a.append([i,j])
z=np.array([a],ndmin=2)

print(z)

[[[0 0]
  [0 1]
  [1 0]
  [1 1]]]


In [12]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_=0
for i in range(len(s)):
    for j in range(len(s[i])):
        sum_=sum_+s[i,j]
print("sum of all element :",sum_)

sum of all element : 45


In [13]:
for i in range(len(s)):
    for j in range(len(s[i])):
          print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2
