In [1]:
import numpy as np

In [4]:
#1
np.__version__

'1.21.5'

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nkmanithia/AppData/anconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nkmanithia/

In [40]:
#2
x=np.array([1,2,3,4,5,0,6])
y=np.array([7,8,3,10,11,12,0])
x+y

array([ 8, 10,  6, 14, 16, 12,  6])

In [24]:
#3
a=np.array([0,0,0,0])
b=np.array([1,2,3,4])
np.any(a)  # false if any element is non zero


False

In [25]:
#4
np.any(b)   #if any element is non_zero

True

In [31]:
#5
np.isfinite(a)  #true if any finite noumber or false infinite

array([ True,  True,  True,  True])

In [33]:
#6 
np.isinf(a) #true if any no is infinite

array([False, False, False, False])

In [32]:
#7
np.isnan(a)

array([False, False, False, False])

In [37]:
#8
x=np.array([1,2,2+1j,1])
print(np.isreal(x))
print(np.iscomplex(x))


[ True  True False  True]
[False False  True False]


In [38]:
#9

In [41]:
#10
a=np.array([1,2,3,5,8,3,8])
b=np.array([3,2,6,8,6,3,6])
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))
print(np.less_equal(a,b))

[False False False False  True False  True]
[False  True False False  True  True  True]
[ True False  True  True False False False]
[ True  True  True  True False  True False]


In [50]:
#11 
arr=np.array([1,7,13,105])
print(x.size)
print(x.itemsize)
print(x.size * x.itemsize)  #total size occupied

7
4
28


In [61]:
#12
print(np.array([np.zeros(10),np.ones(10),np.ones(10)*5]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [ ]:
#13
